curl -XPOST -H "content-type: application/xml" https://rhms2.callippus.co.uk/api/BootTimeStatus -d '<BOOT_STATUS>
      <SerialNo>23456</SerialNo>
      <Date_Time>25012020123230</Date_Time>
      <DOT>
            <Date>07012019</Date>
            <Slot1>60</Slot1>
            <Slot2>200</Slot2>
            <Slot3>160</Slot3>
            <Slot4>180</Slot4>
      </DOT>      
      <Printer>Yes</Printer>
      <Bluetooth>Yes</Bluetooth>
      <WIFI>Yes</WIFI>
      <Camera>Yes</Camera>
      <AUDIO>Success</AUDIO>
      <BatteryInfo>
            <Date>07012019</Date>
            <Day_worked_mins>600</Day_worked_mins>
            <Day_adapter_mins>180</Day_adapter_mins>
            <Day_charged_mins>120</Day_charged_mins>
            <Day_discharged_mins>420</Day_discharged_mins>
      </BatteryInfo>
      <ArrayofApplications>
            <Application>
                  <ApplicationType>PDS</ApplicationType>
                  <ApplicationName>PDS App</ApplicationName>
                  <ApplicationVer>1.0</ApplicationVer>
            </Application>
            <Application>
                  <ApplicationType>PDS</ApplicationType>
                  <ApplicationName>APPDS</ApplicationName>
                  <ApplicationVer>2.0</ApplicationVer>
            </Application>
            <Application>
                  <ApplicationType>PDS</ApplicationType>
                  <ApplicationName>testing</ApplicationName>
                  <ApplicationVer>1.0</ApplicationVer>
            </Application>
      </ArrayofApplications>
      <FirmwareName>4</FirmwareName>
      <FirmwareVersion>2.4</FirmwareVersion>
      <IritechRDVer>1.0</IritechRDVer>
      <BiomRDVer>2.0</BiomRDVer>
      <FPSRDVer>1.7</FPSRDVer>
      <ExternalMem>
            <Total>3.7GB</Total>
            <Use>32.0KB</Use>
            <Free>3.7GB</Free>
      </ExternalMem>
      <Usbdevice>
            <Total>7.1GB</Total>
            <Use>489.0MB</Use>
            <Free>6.3GB</Free>
      </Usbdevice>
      <SIM1CCIDnumber>89914904900017615117</SIM1CCIDnumber>
      <SIM1Operator>airtel</SIM1Operator>
      <SIM2CCIDnumber>89914904900017615118</SIM2CCIDnumber>
      <SIM2Operator>idea</SIM2Operator>
</BOOT_STATUS>'
