curl -XPOST -H "content-type: application/xml" https://rhms2.callippus.co.uk/api/HealthStatus -d '<HealthStatus>
    <SerialNo>23456</SerialNo>
    <Date_Time>25012020123230</Date_Time>
    <GPS>
        <Latitude>17.445678</Latitude>
        <Longitude>78.465656</Longitude>
        <Captured_Time>25012020123230</Captured_Time>
    </GPS>
    <IRIS>IRITECH</IRIS>
    <PaperStatus>Present</PaperStatus>
    <RTC>Failure</RTC>
    <Battery>Charged</Battery>
    <Adapter>Connected</Adapter>
    <Comm>GSM</Comm>
    <SIM1db>12</SIM1db>
    <SIM2db>No</SIM2db>
    <SIM1SignalMode>3G</SIM1SignalMode>
    <SIM2SignalMode>No</SIM2SignalMode>
    <System_memory>
        <Total>1007.9M</Total>
        <Use>35.7M</Use>
        <Free>921.0M</Free>
    </System_memory>
    <InternalMem_Sysuser>
        <Total>1007.9M</Total>
        <Use>35.7M</Use>
        <Free>921.0M</Free>
    </InternalMem_Sysuser>
    <InternalMem_Jffs2>
        <Total>3.9G</Total>
        <Use>139.5M</Use>
        <Free>3.6G</Free>
    </InternalMem_Jffs2>
    <RAM>
        <Total>1008MB</Total>
        <Use>71MB</Use>
        <Free>937MB</Free>
    </RAM>
</HealthStatus>'
